In [1]:
print("Sample Tensoflow Learning")

Sample Tensoflow Learning


In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available using GPU")


GPU is available
Using GPU: Tesla T4


Creating a Tensor

In [ ]:
#using empty
torch.empty(2,3)

tensor([[-2.3235e-06,  4.5077e-41,  2.6231e-06],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#manual tensor
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [ ]:
#Other ways

torch.arange(1,10)
torch.linspace(1,10,10) #linearly spaced
torch.eye(3) #identity matrix
torch.full((3,3),5) #full matrix with element specified

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Tensor Shapes

In [ ]:
x = torch.tensor([1,23,4], dtype=torch.float32)
x.shape

torch.Size([3])

In [ ]:
#Creating tensor with same shape
torch.empty_like(x)
torch.zeros_like(x)
torch.ones_like(x)
torch.rand_like(x) #This always generates the float

tensor([0.8238, 0.5557, 0.9770])

Tensor Datatype

In [ ]:
#find datatype
x.dtype

torch.float32

In [ ]:
#assign datatypes
torch.tensor([1,2,3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#using .to() to change the datatype
x.to(torch.int32)

tensor([ 1, 23,  4], dtype=torch.int32)

# **Mathematical operations**

Scalar operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])

In [ ]:
#Mathematical op on each element of a tensor
x+2
torch.abs(x)
torch.round(x)
torch.ceil(x)
torch.floor(x)
torch.clamp(x, min=2, max =3) # < than 2 will be 2
                              # > 3 will be 3

tensor([[2., 2.],
        [2., 2.]])

Element wise oepration of multiple tensors

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
a+b

tensor([[1.2636, 1.2920, 1.8231],
        [1.5946, 1.0814, 1.2905]])

Reduction operations

In [ ]:
#sum of all
torch.sum(x)
#Sum alons the columns
torch.sum(x, dim=0)
#Sum along the rows
torch.sum(x, dim=1)

tensor([0.9429, 0.7749])

In [ ]:
#mean
torch.mean(x) #requires the data to be in float32
#mean along col and such
torch.mean(x, dim=0)

tensor([0.3851, 0.4738])

In [ ]:
#median
torch.median(x) #requires the data to be in float32
#mean along col and such
torch.median(x, dim=0)

torch.return_types.median(
values=tensor([0.2426, 0.2472]),
indices=tensor([0, 1]))

In [ ]:
#standard deviation
torch.std(x) #requires the data to be in float32
#mean along col and such
torch.std(x, dim=0)

tensor([0.2016, 0.3204])

In [ ]:
#variance
torch.var(x) #requires the data to be in float32
#mean along col and such
torch.var(x, dim=0)

tensor([0.0406, 0.1027])

In [ ]:
#argmax will give the position of the largest element
x = torch.rand(2,3)
torch.argmax(x)
#argmin will give the position of the smallest element
x = torch.rand(2,3)
torch.argmin(x)

tensor(0)

Matrix operations

In [ ]:
#matmul for matrix multiplication
a = torch.rand(2,3)
b = torch.rand(3,4)
torch.matmul(a,b)

tensor([[0.3289, 1.0394, 0.9492, 1.0254],
        [0.2125, 0.7666, 0.7372, 0.5990]])

In [ ]:
#dot product requires the 1D tensors i.e vectors
a = torch.rand(3)
b = torch.rand(3)
torch.dot(a,b)

tensor(0.5343)

In [ ]:
#Transpose needs at least 2D tensor
a = torch.rand(2,3)
b = torch.transpose(a, 0, 1)
b

tensor([[0.9127, 0.9991],
        [0.6818, 0.1133],
        [0.1953, 0.0135]])

In [ ]:
#determinant
a = torch.rand(3,3)
torch.det(a)

tensor(-0.0641)

In [ ]:
#inverse
torch.inverse(a)

tensor([[-7.9516,  1.3970, 10.5329],
        [-2.5692,  1.6216,  2.1871],
        [ 5.1432, -1.0257, -5.0100]])

Comparision operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
a>b
a<b
a=b
a>=b

tensor([[True, True, True],
        [True, True, True]])

Special Functions

In [ ]:
 torch.manual_seed(100)
 k = torch.rand(2,3)
 torch.sqrt(k)
 torch.softmax(k, dim = 1)
 torch.log(k)
 torch.relu(k)
 torch.sigmoid(k)

tensor([[0.5279, 0.6934, 0.5653],
        [0.6187, 0.6630, 0.6800]])

IN PLACE OPERATIONS

In [ ]:
torch.manual_seed(100)
m = torch.rand(2,3)
n = torch.rand(2,3)
m.add_(n)
m.sub_(n)
m.mul_(n)
m.div_(n)
m.relu_()
m.sigmoid_()
m

tensor([[0.5279, 0.6934, 0.5653],
        [0.6187, 0.6630, 0.6800]])

COPYING A TENSOR

In [ ]:
torch.manual_seed(100)
a = torch.rand(2,3)
b = a # This is reference assigned
id(a)
id(b)

135165403586512

In [ ]:
#Solution is to clone
b = a.clone()
id(b)

135165389970640

TENSOR OPERATIONS ON GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
device = torch.device('cuda')

In [10]:
#Creating a new tensor on GPU
torch.manual_seed(100)
a = torch.rand(2,3)
aG = torch.rand((2,3),device = device)
print(a)
print(aG)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')


In [13]:
#Moving the tensor of CPU to the GPU
aNew = a.to(device)
print(aNew)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]], device='cuda:0')


Comparing the processing time for tensor in CPU vs GPU

In [16]:
import time

In [28]:
size = 10000
torch.manual_seed(100)
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)
startTime = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
endTime = time.time()
CPUtime = endTime - startTime
print(f"{CPUtime}")

17.050874710083008


In [29]:
size = 10000
torch.manual_seed(100)
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')
startTime = time.time()
result_cpu = torch.matmul(matrix_gpu1, matrix_gpu2)
endTime = time.time()
GPUtime = endTime - startTime
print(f"{GPUtime}")

0.0002722740173339844


In [30]:
speedUp = CPUtime/GPUtime
print(f"GPU is {speedUp} times faster than CPU")

GPU is 62623.950963222414 times faster than CPU


RESHAPING THE TENSORS

In [37]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [42]:
# Product should be same as that of original dimension
b = a.reshape(2,2,2,2)
b

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [43]:
#Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
#Permute
#This will help rotate the dimension's position
c = torch.rand(2,3,4)
c.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [51]:
#Unsqueeze
#Adds a new dimension to a given position
c = torch.rand(226,226,3) #sample image
c.unsqueeze(1).shape #Position of the dimension
#Use case
    # To send batches of the tensors to the model you are training

torch.Size([226, 1, 226, 3])

In [60]:
#Squeeze
##Removes the 1 dimensions present
##Used to remove the extra dimension caused by unsqueezing for eg
d = torch.rand(2,1,20)
print(d.shape)
# print(d)
e = d.squeeze(1)
print(e.shape)
f = d.squeeze(0)
print(f.shape)
# print(e)

torch.Size([2, 1, 20])
torch.Size([2, 20])
torch.Size([2, 1, 20])


NUMPY AND PYTORCH

In [61]:
import numpy as np

In [66]:
# You can convert numpy arrays to pytorch tensor and vice versa
a = torch.rand(1,2,3)
b = a.numpy()
type(b)

numpy.ndarray

In [67]:
c = torch.from_numpy(b)
c.type

<function Tensor.type>