In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
# Creating a synthetic classification dataset using sklearn
X,y =make_classification(
    n_samples=10, #No of samples
    n_features=2, #No of features
    n_informative=2, #No of informative features
    n_redundant=0, #No of redundant features
    n_classes=2, #No of classes
    random_state=42 # For reproducibility
)

In [ ]:
X.shape

(10, 2)

In [ ]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels
  def __len__(self):
    return len(self.features)
  def __getitem__(self, idx):
    #Transformation is performed here

    #
    return self.features[idx], self.labels[idx]

In [ ]:
dataset = CustomDataset(X, y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [ ]:
#DataLoader is an iterable
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [ ]:
for batch_features, batch_labels in dataloader:
  print(batch_features, batch_labels)
  print("--------------------------")

tensor([[-1.9629, -0.9923],
        [-0.7206, -0.9606]]) tensor([0, 0])
--------------------------
tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]]) tensor([1, 0])
--------------------------
tensor([[ 1.8997,  0.8344],
        [ 1.7273, -1.1858]]) tensor([1, 1])
--------------------------
tensor([[ 1.7774,  1.5116],
        [-0.9382, -0.5430]]) tensor([1, 1])
--------------------------
tensor([[-0.5872, -1.9717],
        [-2.8954,  1.9769]]) tensor([0, 0])
--------------------------
