# NUMPY

In [12]:
### Creating the numpy arrays
import numpy as np

In [37]:
arr1 = np.array([1,2,3,4,5])
arr1.shape

(5,)

In [14]:
type(arr1)

numpy.ndarray

In [39]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2.shape
arr2.ndim

2

In [18]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
arr5 = np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
arr6 = np.arange(10,18,2)
arr6

array([10, 12, 14, 16])

In [33]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [35]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

## ATTRIBUTES

In [45]:
arr8.shape

(10,)

In [46]:
arr8.ndim

1

In [41]:
arr8.size

10

In [42]:
arr8.itemsize

8

In [43]:
arr8.dtype

dtype('float64')

In [44]:
arr9 = arr8.astype('int')
arr9.dtype

dtype('int32')

## List V Array

##### MEMORY

In [47]:
lista = range(100)
arr10 = np.arange(100)

In [49]:
import sys

In [52]:
sys.getsizeof(87)

28

In [50]:
print(sys.getsizeof(87)*len(lista))

2800


In [51]:
print(arr10.itemsize*arr10.size)

400


#### SPEED

In [53]:
import time

In [65]:
x = range(10000000)
y = range(10000000,20000000)

start_time = time.time()
c = [x+y for x,y in zip(x,y)]
print(time.time() - start_time)

1.3292431831359863


In [67]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start_time = time.time()
c = a+b ##EASY operation
print(time.time() - start_time)

0.022680044174194336


# INDEXING SLICING AND ITERATION

#### INDEXING

In [70]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [85]:
arr12[:,2:3]
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [87]:
#example extract 9 10 13 14
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [88]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [89]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [90]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# OPERATIONS